apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: demo-veradco

# namePrefix: demo-

resources:
- ../base
- webhooks.yaml

patchesStrategicMerge:
- veradco.yaml
- veradco_conf.yaml
- namespace.yaml