apiVersion: apps/v1
kind: Deployment
metadata:
  name: veradco
  namespace: veradco
spec:
  template:
    metadata:
      labels:
        app: veradco
    spec:
      initContainers:
      - name: veradco-plugins-init
        image: localhost:5001/smartduck/veradco-golang-builder:v0.1.1
      containers:
      - name: veradco-server
        image: localhost:5001/smartduck/veradco:v0.1.1
        args: ["-v=0"]
        env:
        - name: hUSER
          value: "HARBORuser"
        - name: hPW
          value: "HARBORpw"
        - name: "HARBORPCP_DEBUG"
          value: "debug proxy cache populator"