apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: veradco-svc-monitor
  namespace: veradco
  labels:
    app: veradco
spec:
  selector:
    matchLabels:
      app: veradco-monitoring
  endpoints:
  - port: "metrics"