apiVersion: v1
data:
  webhooks.yaml: |
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: veradco-crs
    webhooks:
    - name: veradco-crs.default.svc
      sideEffects: None
      admissionReviewVersions: ["v1"]
      clientConfig:
        service:
          name: veradco
          namespace: veradco
          path: "/validate/others"
        caBundle: "${CA_BUNDLE}"
      rules:
        - operations: ["CREATE", "DELETE"]
          apiGroups: ["smartduck.ovh"]
          apiVersions: ["v1"]
          resources: ["veradcoplugins"]
      failurePolicy: Ignore
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: veradco-pod-validation
    webhooks:
      - name: veradco-pod-validation.default.svc
        sideEffects: None
        admissionReviewVersions: ["v1"]
        clientConfig:
          service:
            name: veradco
            namespace: veradco
            path: "/validate/pods"
          caBundle: "${CA_BUNDLE}"
        rules:
          - operations: ["CREATE", "UPDATE"]
            apiGroups: [""]
            apiVersions: ["v1"]
            resources: ["pods"]
        failurePolicy: Ignore
    ---
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      name: veradco-pod-mutation
    webhooks:
      - name: veradco-pod-mutation.default.svc
        sideEffects: None
        admissionReviewVersions: ["v1"]
        clientConfig:
          service:
            name: veradco
            namespace: veradco
            path: "/mutate/pods"
          caBundle: "${CA_BUNDLE}"
        rules:
          - operations: ["*"]
            apiGroups: ["*"]
            apiVersions: ["v1"]
            resources: ["pods"]
        failurePolicy: Ignore
kind: ConfigMap
metadata:
  name: webhooks
  namespace: veradco