apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: veradco
  labels:
    app.kubernetes.io/name: veradco
    app.kubernetes.io/instance: veradco
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: veradco
    app.kubernetes.io/part-of: veradco
    app.kubernetes.io/managed-by: veradco
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: veradco
  namespace: veradco
  labels:
    app.kubernetes.io/name: veradco
    app.kubernetes.io/instance: veradco
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: veradco
    app.kubernetes.io/part-of: veradco
    app.kubernetes.io/managed-by: veradco
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: veradco
  namespace: veradco
  labels:
    app.kubernetes.io/name: veradco
    app.kubernetes.io/instance: veradco
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: veradco
    app.kubernetes.io/part-of: veradco
    app.kubernetes.io/managed-by: veradco
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veradco
subjects:
  - kind: ServiceAccount
    name: veradco
    namespace: veradco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: veradco
  namespace: veradco
  labels:
    app: veradco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veradco
  template:
    metadata:
      labels:
        app: veradco
    spec:
      serviceAccountName: veradco
      initContainers:
      - name: veradco-pki-init
        image: smartduck/veradco_pki_manager:v0.2.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/certs
        - name: config-volume-webhooks
          mountPath: /conf/
          readOnly: true
        # - name: config-volume
        #   mountPath: /conf_veradco/
        #   readOnly: true
      containers:
      - name: veradco-server
        image: smartduck/veradco:v0.2.0
        imagePullPolicy: Always
        command: ["/app/veradcod"]
        # command: ["/bin/sh"]
        args: ["-v=0"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
        ports:
        - containerPort: 8443
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "100m"
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/certs
          readOnly: true
        - name: config-volume
          mountPath: /conf/
          readOnly: true
      volumes:
      - name: tls-certs
        emptyDir: {}
      - name: config-volume
        configMap:
          name: veradco
      - name: config-volume-webhooks
        configMap:
          name: webhooks
---
apiVersion: v1
kind: Service
metadata:
  name: veradco
  namespace: veradco
spec:
  selector:
    app: veradco
  ports:
    - port: 443
      targetPort: 8443