# refer to https://dev.to/thenjdevopsguy/creating-a-custom-resource-definition-in-kubernetes-2k7o
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: veradcoplugins.smartduck.ovh
spec:
  group: smartduck.ovh
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                plugin:
                  type: string
  scope: Namespaced
  names:
    kind: VeradcoPlugin
    plural: veradcoplugins
    singular: veradcoplugin
    shortNames:
    - veraplug
