apiVersion: apps/v1
kind: Deployment
metadata:
  name: veradco
  namespace: veradco
spec:
  template:
    metadata:
      labels:
        app: veradco
    spec:
      containers:
      - name: veradco-server
        image: localhost:5001/smartduck/veradco-standalone:0.1
        env:
        - name: hUSER
          value: "HARBORuser"
        - name: hPW
          value: "HARBORpw"
        - name: "HARBORPCP_DEBUG"
          value: "debug proxy cache populator"