apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: veradco-crs
webhooks:
- name: veradco-crs
  sideEffects: None
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: veradco
      namespace: veradco
      path: "/validate/pods"
    caBundle: "${CA_BUNDLE}"
  rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: ["smartduck.ovh"]
      apiVersions: ["v1"]
      resources: ["veradcoplugins"]
  failurePolicy: Ignore