apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../grpc_base
- deploy_plugin_adddummysidecar.yaml
- deploy_plugin_forbidtag.yaml
- deploy_plugin_valid.yaml

patchesStrategicMerge:
- veradco.yaml
- veradco_conf.yaml