apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../grpc_base
- deploy_plugin_adddummysidecar.yaml
- deploy_plugin_forbidtag.yaml
- deploy_plugin_valid.yaml
- plugins_ns.yaml

patches:
- path: veradco.yaml
- path: veradco_conf.yaml
- path: cmwebhooks.yaml