apiVersion: apps/v1
kind: Deployment
metadata:
  name: veradco
  namespace: veradco
spec:
  template:
    metadata:
      labels:
        app: veradco
    spec:
      initContainers:
      - name: veradco-pki-init
        image: localhost:5001/smartduck/veradco_pki_manager:v0.2.0
      containers:
      - name: veradco-server
        # args: ["-v=10"]
        args: ["-v=4"]
        image: localhost:5001/smartduck/veradco:v0.2.0