apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummyplugin2
  namespace: default
  labels:
    app: dummyplugin2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummyplugin2
  template:
    metadata:
      labels:
        app: dummyplugin2
    spec:
      containers:
      - name: dummyplugin2
        image: localhost:5001/smartduck/dummy-grpc-plugin:0.1
        command: ["/app/dummy"]
        args: ["-port=50052"]
        imagePullPolicy: Always
        ports:
        - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: dummyplugin2
  namespace: default
spec:
  selector:
    app: dummyplugin2
  ports:
    - port: 50052
      targetPort: 50052