apiVersion: apps/v1
kind: Deployment
metadata:
  name: veradco
  namespace: veradco
  labels:
    app: veradco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veradco
  template:
    metadata:
      labels:
        app: veradco
    spec:
      initContainers:
      - name: plugins-init
        image: localhost:5001/smartduck/veradco_plugins:0.1
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "cp -R /plugins/* /plugs"]
        volumeMounts:
        - name: plugins-volume
          mountPath: "/plugs"
      containers:
      - name: server
        image: localhost:5001/smartduck/veradco:0.1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/certs
          readOnly: true
        - name: config-volume
          mountPath: /conf/
          readOnly: true
        - name: plugins-volume
          mountPath: /plugs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: veradco-tls
      - name: config-volume
        configMap:
          name: veradco
      - name: plugins-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: veradco
  namespace: veradco
spec:
  selector:
    app: veradco
  ports:
    - port: 443
      targetPort: 8443