apiVersion: v1
kind: ConfigMap
metadata:
  name: veradco
  namespace: veradco
data:
  veradco.yaml: |
    plugins:
    - name: "plug1"
      path: "/plugins/plug1.so"
      resources:
      - "Pod"
      operations:
      - "CREATE"
      dryRun: false
      configuration: |
        This plugin does not have configuration
        That's like that!
      scope: "Validating" 