apiVersion: v1
kind: ConfigMap
metadata:
  name: veradco
  namespace: veradco
data:
  veradco.yaml: |
    plugins:
    - name: "plug1"
      path: "/plugins/plug1.so"
      resources:
      - "Pod"
      operations:
      - "CREATE"
      configuration: "/conf/plug1.yaml"
      scope: "Validating" 