apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-example
  namespace: ds-ns
  labels:
    app: daemonset-example
spec:
  selector:
    matchLabels:
      app: daemonset-example
  template:
    metadata:
      labels:
        app: daemonset-example
        nodegp: ng-1
      annotations:
        owner: toto
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "10000"