apiVersion: v1
kind: Pod
metadata:
  name: webserver3
  labels:
    nodegp: ng-1
  annotations:
    owner: atoto
spec:
  containers:
    - name: webserver
      image: nginx:alpine
      ports:
        - containerPort: 80
