apiVersion: v1
kind: Pod
metadata:
  name: webserver4
  namespace: special
  labels:
    nodegp: ng-1
    owner: Me
    test: aa
  annotations:
    owner: atoto
spec:
  containers:
    - name: webserver
      image: nginx:alpine
      ports:
        - containerPort: 80
