apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: special
  labels:
    nodegp: ng-1
    owner: Me
  annotations:
    owner: toto
spec:
  containers:
    - name: webserver
      image: nginx:alpine
      ports:
        - containerPort: 80
